# Generated by Django 3.2 on 2021-04-27 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('pulse_rate', models.IntegerField(verbose_name='ЧПП - в покое')),
                ('index_of_rufe', models.IntegerField(verbose_name='Проба Руффье')),
                ('coefficient_of_endurance', models.FloatField(verbose_name='Коэффициент выносливости')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
