# Generated by Django 3.2 on 2021-04-27 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'verbose_name': 'Статистический показатель', 'verbose_name_plural': 'Статистические показатели'},
        ),
        migrations.AlterField(
            model_name='indicator',
            name='coefficient_of_endurance',
            field=models.FloatField(blank=True, null=True, verbose_name='Коэффициент выносливости'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='index_of_rufe',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проба Руффье'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='pulse_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='ЧПП - в покое'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Спортсмен'),
        ),
    ]
