# Generated by Django 3.2 on 2021-04-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_auto_20210428_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='coefficient_of_endurance',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Коэффициент выносливости'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='index_of_rufe',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Проба Руффье'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='pulse_rate',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ЧПП - в покое'),
        ),
    ]
