# Generated by Django 3.2 on 2021-04-28 12:37

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indicators', '0003_auto_20210428_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 28, 12, 37, 1, 540669, tzinfo=utc), primary_key=True, serialize=False, verbose_name='Дата норматива'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='indicator',
            unique_together={('user', 'date')},
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='id',
        ),
    ]
