# Generated by Django 3.2 on 2021-04-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_auto_20210428_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='date',
            field=models.DateField(default='0', primary_key=True, serialize=False, verbose_name='Дата норматива'),
        ),
    ]
