# Generated by Django 3.2 on 2021-04-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_alter_indicator_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='id',
            field=models.IntegerField(default='888', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicator',
            name='date',
            field=models.DateField(default='2012-04-12', verbose_name='Дата норматива'),
        ),
    ]
