# Generated by Django 3.2 on 2021-04-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_alter_indicator_id'),
        ('indicators', '0008_alter_indicator_id'),
    ]

    operations = [
    ]
