# Generated by Django 3.2 on 2021-04-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0009_merge_0002_alter_indicator_id_0008_alter_indicator_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='id',
        ),
        migrations.AlterField(
            model_name='indicator',
            name='date',
            field=models.DateField(default='2012-04-12', primary_key=True, serialize=False, verbose_name='Дата норматива'),
        ),
    ]
