# Generated by Django 3.2 on 2021-04-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0010_auto_20210428_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='attack_efficiency',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Коэффициент эффективности атакующих действий'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='emotional_stability',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Коэффициент эмоциональной устойчивости'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='protective_actions',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Коэффициент эффективности защитных действий'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='pullups',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Подтягивания'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='push_ups',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Отжимания'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='second_test',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Тест "10 секунд"'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='sit_up',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Пресс "складка"'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='thermometer_test',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Тест "Градусник"'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='versatility_technical_actions',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Коэффициент объема технических действий'),
        ),
    ]
