# Generated by Django 3.2 on 2021-04-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0011_auto_20210429_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicator',
            name='date',
            field=models.DateField(default='2012-04-12', verbose_name='Дата норматива'),
        ),
    ]
