# Generated by Django 3.2 on 2021-04-30 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indicators', '0012_auto_20210429_0249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'verbose_name': 'Физиологическая подготовленность', 'verbose_name_plural': 'Физиологическая подготовленность'},
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='attack_efficiency',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='emotional_stability',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='protective_actions',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='pullups',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='push_ups',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='second_test',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='sit_up',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='thermometer_test',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='versatility_technical_actions',
        ),
        migrations.CreateModel(
            name='TacticaIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2012-04-12', verbose_name='Дата норматива')),
                ('versatility_technical_actions', models.IntegerField(blank=True, default=0, null=True, verbose_name='Коэффициент объема технических действий')),
                ('attack_efficiency', models.IntegerField(blank=True, default=0, null=True, verbose_name='Коэффициент эффективности атакующих действий')),
                ('protective_actions', models.IntegerField(blank=True, default=0, null=True, verbose_name='Коэффициент эффективности защитных действий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Спортсмен')),
            ],
            options={
                'verbose_name': 'Тактическая подготовленность',
                'verbose_name_plural': 'Тактическая подготовленность',
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PsyIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2012-04-12', verbose_name='Дата норматива')),
                ('thermometer_test', models.FloatField(blank=True, default=0, null=True, verbose_name='Тест "Градусник"')),
                ('second_test', models.FloatField(blank=True, default=0, null=True, verbose_name='Тест "10 секунд"')),
                ('emotional_stability', models.FloatField(blank=True, default=0, null=True, verbose_name='Коэффициент эмоциональной устойчивости')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Спортсмен')),
            ],
            options={
                'verbose_name': 'Психологическая подготовленность',
                'verbose_name_plural': 'Психологическая подготовленность',
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PhysicalIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2012-04-12', verbose_name='Дата норматива')),
                ('pullups', models.IntegerField(blank=True, default=0, null=True, verbose_name='Подтягивания')),
                ('push_ups', models.IntegerField(blank=True, default=0, null=True, verbose_name='Отжимания')),
                ('sit_up', models.IntegerField(blank=True, default=0, null=True, verbose_name='Пресс "складка"')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Спортсмен')),
            ],
            options={
                'verbose_name': 'Физическая подготовленность',
                'verbose_name_plural': 'Физическая подготовленность',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
