# Generated by Django 3.2 on 2021-04-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0013_auto_20210430_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='blood_circulation',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Коэффициент экономичности кровообращения'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='clinostatic_test',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Клиностатическая проба'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='orthostatic_test',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Ортостатическая проба'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='rosenthal_test',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Проба Розенталя'),
        ),
    ]
