# Generated by Django 3.2 on 2021-04-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0014_auto_20210430_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalindicator',
            name='acceleration',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Ускорение 100м (c)'),
        ),
        migrations.AddField(
            model_name='physicalindicator',
            name='blow_strength',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Сила ударов (%)'),
        ),
        migrations.AddField(
            model_name='physicalindicator',
            name='bridge',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='"Мостик" (см)'),
        ),
        migrations.AddField(
            model_name='physicalindicator',
            name='coordination',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Ккс (%)'),
        ),
        migrations.AddField(
            model_name='physicalindicator',
            name='endurance',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Выносливость (%)'),
        ),
        migrations.AddField(
            model_name='physicalindicator',
            name='flexibility',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Гибкость (%)'),
        ),
        migrations.AddField(
            model_name='physicalindicator',
            name='long_jump',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Прыжок в длину с места'),
        ),
        migrations.AddField(
            model_name='physicalindicator',
            name='physical_fitness',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='КсФП (%)'),
        ),
        migrations.AddField(
            model_name='physicalindicator',
            name='scope_action',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Отжимания'),
        ),
        migrations.AddField(
            model_name='physicalindicator',
            name='shuttle_run',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Челночный бег 4х9м (с)'),
        ),
        migrations.AddField(
            model_name='physicalindicator',
            name='six_minute_run',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='6-ти минутный бег (м)'),
        ),
        migrations.AddField(
            model_name='physicalindicator',
            name='twine',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='"Шпагат" (см)'),
        ),
    ]
