# Generated by Django 3.2 on 2021-04-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0015_auto_20210430_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='tacticaindicator',
            name='adjustment_factor',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Коэффициент перестройки тактики'),
        ),
        migrations.AddField(
            model_name='tacticaindicator',
            name='chosen_tactics',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Коэффициент избранной тактики'),
        ),
        migrations.AddField(
            model_name='tacticaindicator',
            name='performance_ratio',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Коэффициент результативности'),
        ),
        migrations.AddField(
            model_name='tacticaindicator',
            name='preparatory_actions',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Коэффициент подготовительных тактических действий'),
        ),
        migrations.AddField(
            model_name='tacticaindicator',
            name='scope_tactical_action',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Коэффициент объема тактических действий'),
        ),
        migrations.AddField(
            model_name='tacticaindicator',
            name='situational_actions',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Коэффициент ситуативных тактических действий'),
        ),
        migrations.AddField(
            model_name='tacticaindicator',
            name='tactical_action',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Тактическая подготовленность'),
        ),
        migrations.AddField(
            model_name='tacticaindicator',
            name='technical_readiness',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Техническая подготовленность'),
        ),
        migrations.AddField(
            model_name='tacticaindicator',
            name='versatility_actions',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Разносторонность тактических действий'),
        ),
        migrations.AddField(
            model_name='tacticaindicator',
            name='warfare_ratio',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Коэффициент эффективности боевых действий'),
        ),
    ]
