# Generated by Django 3.2 on 2021-04-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0016_auto_20210430_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='psyindicator',
            name='courage_ratio',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Коэффициент смелости'),
        ),
        migrations.AddField(
            model_name='psyindicator',
            name='persistence_ratio',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Коэффициент настойчивости'),
        ),
    ]
