# Generated by Django 3.2 on 2021-05-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0018_auto_20210430_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'permissions': (('can_add_func_indicator', 'Set book as returned'),), 'verbose_name': 'Функциональная подготовленность', 'verbose_name_plural': 'Функциональная подготовленность'},
        ),
    ]
