# Generated by Django 3.2 on 2021-05-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0020_alter_indicator_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'verbose_name': 'Функциональная подготовленность', 'verbose_name_plural': 'Функциональная подготовленность'},
        ),
    ]
