# Generated by Django 3.2 on 2021-05-22 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0022_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
