# Generated by Django 3.2 on 2021-05-22 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indicators', '0023_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportsmen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sportsmen', to=settings.AUTH_USER_MODEL, verbose_name='Спортсмен')),
                ('trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to=settings.AUTH_USER_MODEL, verbose_name='Спортсмен')),
            ],
            options={
                'verbose_name': 'Список спортсменов у тренера',
            },
        ),
    ]
