# Generated by Django 3.2 on 2021-05-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0028_alter_profile_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='trainer',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
