# Generated by Django 3.2 on 2021-05-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0030_alter_profile_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='trainer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
