# Generated by Django 3.2 on 2021-05-22 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indicators', '0034_remove_profile_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trener', to=settings.AUTH_USER_MODEL, verbose_name='Относится к тренеру'),
        ),
    ]
