# Generated by Django 3.2 on 2021-05-28 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0035_profile_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=256, verbose_name='Категория')),
                ('excellent', models.IntegerField(blank=True, default=0, null=True, verbose_name='Отлично')),
                ('okay', models.IntegerField(blank=True, default=0, null=True, verbose_name='Хорошо')),
                ('fine', models.IntegerField(blank=True, default=0, null=True, verbose_name='Нормально')),
                ('satisfactorily', models.IntegerField(blank=True, default=0, null=True, verbose_name='Удовлитворительно')),
                ('unsatisfactory', models.IntegerField(blank=True, default=0, null=True, verbose_name='Неудовлетворительно')),
                ('excellent_border', models.IntegerField(blank=True, default=0, null=True, verbose_name='Отлично')),
                ('okay_border', models.IntegerField(blank=True, default=0, null=True, verbose_name='Хорошо')),
                ('fine_border', models.IntegerField(blank=True, default=0, null=True, verbose_name='Нормально')),
                ('satisfactorily_border', models.IntegerField(blank=True, default=0, null=True, verbose_name='Удовлитворительно')),
                ('unsatisfactory_border', models.IntegerField(blank=True, default=0, null=True, verbose_name='Неудовлетворительно')),
                ('functional_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='func', to='indicators.indicator', verbose_name='Функциональный показатель')),
                ('physical_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physical', to='indicators.physicalindicator', verbose_name='Физический показатель')),
                ('psy_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psy', to='indicators.psyindicator', verbose_name='Психический показатель')),
                ('tactical_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tactical', to='indicators.tacticaindicator', verbose_name='Технико-тактический показатель')),
            ],
        ),
    ]
