# Generated by Django 3.2 on 2021-05-28 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0036_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListIndicator',
            fields=[
                ('name_indicator', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='grade',
            name='functional_indicator',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='physical_indicator',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='psy_indicator',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='tactical_indicator',
        ),
        migrations.AddField(
            model_name='grade',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psy', to='indicators.listindicator', verbose_name='Статистический показатель'),
        ),
    ]
