# Generated by Django 3.2 on 2021-05-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0037_auto_20210528_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='indicator',
            field=models.CharField(blank=True, default='ЧПП', max_length=256, null=True, verbose_name='Статистический показатель'),
        ),
    ]
