# Generated by Django 3.2 on 2021-06-04 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0040_alter_indicator_pulse_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата норматива'),
        ),
    ]
