# Generated by Django 3.2 on 2021-06-04 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0041_alter_indicator_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalindicator',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата норматива'),
        ),
        migrations.AlterField(
            model_name='psyindicator',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата норматива'),
        ),
        migrations.AlterField(
            model_name='tacticaindicator',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата норматива'),
        ),
    ]
